recipes2/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views

from . import views

app_name = "recipes2"
urlpatterns = [
    path("", views.home, name="home"),
    path("csrf/", views.get_csrf_token, name="get_csrf_token"),
    path("accounts/login/", auth_views.LoginView.as_view(template_name="admin/login.html"), name="login"),
    path("accounts/login/success/", views.accounts_login_success, name="accounts_login_success"),
    path("quick-search/", views.quick_search, name="quick_search"),
    path("q/", RedirectView.as_view(pattern_name='recipes2:quick_search', permanent=False)),
    path("index/", views.index, name="index"),
    path("gallery/", views.gallery, name="gallery"),
    path("explore/", views.explore, name="explore"),
    path("contents/", views.contents, name="contents"),
    path("ingredient-price/add/", views.add_ingredient_price, name="add_ingredient_price"),
    path("api/latest-ingredient/", views.get_latest_ingredient_price, name="latest_ingredient"),
    path("api/ingredient-prices/", views.get_ingredient_prices, name="ingredient_prices"),
    path("diagnostics/", views.diagnostics_index, name="diagnostics_index"),
    path("diagnostics/<slug:module_name>/", views.diagnostics_report, name="diagnostics_report"),
    path("<slug:recipe_slug>/", views.viewer, name="viewer"),
    path("<slug:recipe_slug>/diary/add/", views.add_diary_entry, name="add_diary_entry"),
]

recipes2/templates/recipes2/viewer/partials/_cost_overlay.html
{% extends 'recipes2/viewer/partials/_overlay.html' %}
{% load recipe_extras %}

{% block content %}
  <table class="recipe-cost" onclick="event.stopPropagation()">
    <thead>
      <tr>
        <th>Name</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Cost</th>
      </tr>
    </thead>
    <tbody>
      {% for cost in item_costs %}
        <tr>
          <td>{{ cost.ingredient_name }}</td>
          <td>
            {% if cost.item_quantity != 0 %}
              {{ cost.item_quantity|floatformat:'-3'|detrail|wrap_scalable }}
            {% endif %}
            {{ cost.item_unit }}
          </td>
          <td>
            {% if cost.success %}
              ${{ cost.price|floatformat:'-2'|detrail }} per {{ cost.price_quantity|floatformat:'-3'|detrail }} {{ cost.price_unit }}
            {% else %}
              &ndash;
            {% endif %}
          </td>
          <td>
            {% if cost.success %}
              ${{ cost.amount|floatformat:'-2'|detrail|wrap_scalable }}
            {% else %}
              &ndash;
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
    <tfoot>
      <tr>
        <td colspan="3">Total</td>
        <td class="total-cell">${{ total_cost|floatformat:'-2'|detrail|wrap_scalable }}</td>
      </tr>
    </tfoot>
  </table>
{% endblock %}

recipes2/templates/recipes2/viewer/partials/_diary_overlay.html
{% extends 'recipes2/viewer/partials/_overlay.html' %}
{% load recipe_extras %}

{% block content %}
  <dl class="recipe-diary" onclick="event.stopPropagation()">
    {% if diaryentries.all.count > 0 %}
      {% regroup diaryentries.all by date|date:'Y-m-d' as diaryentries_by_day %}
      {% for day in diaryentries_by_day %}
        <dt>{{ day.grouper }}</dt>
        <dd>
          {% for diaryentry in day.list %}
            <strong>{{ diaryentry.date|date:'H:i' }}</strong>
            {% if diaryentry.user and diaryentry.user.username != 'alrus' %}
              <span class="diary-username">&lt;{{ diaryentry.user.username }}&gt;</span>
            {% endif %}
            {{ diaryentry.content|smartquote|safe|render_markdown }}
          {% endfor %}
        </dd>
      {% endfor %}
    {% else %}
      <dd id="diary-empty-message">[all empty, there are no diary entries yet]</dd>
    {% endif %}
    <dt>{% now "Y-m-d" %}</dt>
    <dd class="form">
      <strong id="diary-current-time">{% now 'H:i' %}</strong>
      <span id="diary-input" contenteditable="true"></span><span id="diary-add-login-tip" class="hidden">you might need to log in <a href="{% url 'recipes2:login' %}" target="_blank" class="clickable">here</a></span>
    </dd>
  </dl>
{% endblock %}

recipes2/templates/recipes2/viewer/partials/_image_overlay.html
{% extends 'recipes2/viewer/partials/_overlay.html' %}

{% block content %}
  {% with images=recipe.images.all %}
    {% if images %}
      <div class="carousel-container" onclick="event.stopPropagation()">
        {% with image=images|first %}
          <img id="main-image" src="{{ image.image.url }}" alt="{{ image.alt_text }}" />
        {% endwith %}
        <div class="thumbnail-strip">
          {% for image in images %}
            <img src="{{ image.image.url }}" alt="{{ image.alt_text }}" data-full-src="{{ image.image.url }}" class="{% if forloop.first %}selected{% endif %}" onclick="selectImage(event)" />
          {% endfor %}
        </div>
      </div>
    {% endif %}
  {% endwith %}
{% endblock %}

recipes2/templates/recipes2/viewer/partials/_overlay.html
<div class="overlay-background hidden" data-overlay="{{ overlay_name }}" onclick="toggleOverlay(event)" id="{{ overlay_name }}">
  <h2 class="overlay-print-heading">{{ overlay_title }}</h2>
  <div class="overlay-content-wrapper-wrapper">
    <div class="overlay-content-wrapper">
      {% block content %}
        you need to override this block
      {% endblock %}
      <div class="overlay-close-wrapper">
        <button class="overlay-close">Close</button>
      </div>
    </div>
  </div>
</div>