recipes2/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views

from . import views

app_name = "recipes2"
urlpatterns = [
    path("", views.home, name="home"),
    path("csrf/", views.get_csrf_token, name="get_csrf_token"),
    path("accounts/login/", auth_views.LoginView.as_view(template_name="admin/login.html"), name="login"),
    path("accounts/login/success/", views.accounts_login_success, name="accounts_login_success"),
    path("quick-search/", views.quick_search, name="quick_search"),
    path("q/", RedirectView.as_view(pattern_name='recipes2:quick_search', permanent=False)),
    path("index/", views.index, name="index"),
    path("gallery/", views.gallery, name="gallery"),
    path("explore/", views.explore, name="explore"),
    path("contents/", views.contents, name="contents"),
    path("ingredient-price/add/", views.add_ingredient_price, name="add_ingredient_price"),
    path("api/latest-ingredient/", views.get_latest_ingredient_price, name="latest_ingredient"),
    path("api/ingredient-prices/", views.get_ingredient_prices, name="ingredient_prices"),
    path("diagnostics/", views.diagnostics_index, name="diagnostics_index"),
    path("diagnostics/<slug:module_name>/", views.diagnostics_report, name="diagnostics_report"),
    path("<slug:recipe_slug>/", views.viewer, name="viewer"),
    path("<slug:recipe_slug>/diary/add/", views.add_diary_entry, name="add_diary_entry"),
]

recipes2/templates/recipes2/index/index.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>index | yum, yum, yum</title>
    <link rel="stylesheet" href="{% static 'recipes2/master/master.css' %}" />
    <link rel="stylesheet" href="{% static 'recipes2/master/columns.css' %}" />
    <link rel="stylesheet" href="{% static 'recipes2/index/index.css' %}" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>

  <body>
    <header class="header-bar">
      <h1>Index</h1>
      <ul class="icons-list">
        <li class="icon-wrapper">
          <a href="{% url 'recipes2:home' %}">
            <svg height="27" xmlns="http://www.w3.org/2000/svg" width="27" viewBox="0 0 576 512" aria-labelledby="home-icon" class="icon" role="img">
              <title id="home-icon">Go to home page</title>
              <path d="M575.8 255.5c0 18-15 32.1-32 32.1h-32l.7 160.2c0 2.7-.2 5.4-.5 8.1V472c0 22.1-17.9 40-40 40H456c-1.1 0-2.2 0-3.3-.1c-1.4 .1-2.8 .1-4.2 .1H416 392c-22.1 0-40-17.9-40-40V448 384c0-17.7-14.3-32-32-32H256c-17.7 0-32 14.3-32 32v64 24c0 22.1-17.9 40-40 40H160 128.1c-1.5 0-3-.1-4.5-.2c-1.2 .1-2.4 .2-3.6 .2H104c-22.1 0-40-17.9-40-40V360c0-.9 0-1.9 .1-2.8V287.6H32c-18 0-32-14-32-32.1c0-9 3-17 10-24L266.4 8c7-7 15-8 22-8s15 2 21 7L564.8 231.5c8 7 12 15 11 24z"></path>
            </svg>
          </a>
        </li>
      </ul>
    </header>
    <section class="index recipe-list-simple">
      {% regroup index_entries by first_letter as first_letter_entries %}
      {% for group in first_letter_entries %}
        <section>
          <h2>{{ group.grouper }}</h2>
          {% regroup group.list by group as group_entries %}
          {% for group in group_entries %}
            {% if group.list|length == 1 and group.list.0.name == None %}
              <li>
                <a href="{% url 'recipes2:viewer' group.list.0.slug %}">{{ group.grouper }}</a>
              </li>
            {% else %}
              <details>
                <summary>
                  <span class="name">{{ group.grouper }}</span><span class="count"> ({{ group.list|length }})</span>
                </summary>
                <ol>
                  {% for entry in group.list %}
                    <li>
                      <a href="{% url 'recipes2:viewer' entry.slug %}">{{ entry.name }}</a>
                    </li>
                  {% endfor %}
                </ol>
              </details>
            {% endif %}
          {% endfor %}
        </section>
      {% endfor %}
    </section>
  </body>
</html>